import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Base lexical roots across categories
const NOUN_ROOTS = [
  ["abandonment", "/əˈbæn.dən.mənt/", "Sự từ bỏ, bỏ rơi", "Tâm lý & Xã hội", "B2 - Trung cao"],
  ["abbreviation", "/əˌbriː.viˈeɪ.ʃən/", "Chữ viết tắt", "Giáo dục & Trường học", "B1 - Trung cấp"],
  ["abolition", "/ˌæb.əˈlɪʃ.ən/", "Sự bãi bỏ, hủy bỏ", "Luật pháp & Ngoại giao", "C1 - Cao cấp"],
  ["abundance", "/əˈbʌn.dəns/", "Sự dồi dào, phong phú", "Môi trường & Sinh thái", "B2 - Trung cao"],
  ["acceleration", "/əkˌsel.əˈreɪ.ʃən/", "Sự gia tốc, tăng tốc", "Khoa học & Đổi mới", "B2 - Trung cao"],
  ["acceptance", "/əkˈsep.təns/", "Sự chấp thuận, chấp nhận", "Giao tiếp hàng ngày", "A2 - Sơ cấp"],
  ["accessibility", "/əkˌses.əˈbɪl.ə.ti/", "Tính dễ tiếp cận", "Công nghệ & Kỹ thuật số", "B2 - Trung cao"],
  ["acclamation", "/ˌæk.ləˈmeɪ.ʃən/", "Sự hoan nghênh nhiệt liệt", "Nghệ thuật & Văn hóa", "C2 - Thành thạo"],
  ["accomplishment", "/əˈkʌm.plɪʃ.mənt/", "Thành tựu, thành tích", "Kinh doanh & Quản trị", "B1 - Trung cấp"],
  ["accountability", "/əˌkaʊn.təˈbɪl.ə.ti/", "Trách nhiệm giải trình", "Kinh doanh & Quản trị", "C1 - Cao cấp"],
  ["accumulation", "/əˌkjuː.mjəˈleɪ.ʃən/", "Sự tích lũy, dồn lại", "Tài chính & Đầu tư", "B2 - Trung cao"],
  ["accuracy", "/ˈæk.jə.rə.si/", "Độ chính xác", "Khoa học & Đổi mới", "B1 - Trung cấp"],
  ["achievement", "/əˈtʃiːv.mənt/", "Thành tựu, kết quả đạt được", "Giáo dục & Trường học", "A2 - Sơ cấp"],
  ["acknowledgment", "/əkˈnɒl.ɪdʒ.mənt/", "Sự ghi nhận, công nhận", "Học thuật & Nghiên cứu", "B2 - Trung cao"],
  ["acquisition", "/ˌæk.wɪˈzɪʃ.ən/", "Sự mua lại, thâu tóm, tiếp thu", "Kinh tế & Tài chính", "B2 - Trung cao"],
  ["activation", "/ˌæk.tɪˈveɪ.ʃən/", "Sự kích hoạt", "Công nghệ & Kỹ thuật số", "B1 - Trung cấp"],
  ["adaptation", "/ˌæd.æpˈteɪ.ʃən/", "Sự thích nghi, phỏng tác", "Môi trường & Sinh thái", "B2 - Trung cao"],
  ["adequacy", "/ˈæd.ə.kwə.si/", "Sự đầy đủ, thỏa đáng", "Sức khỏe & Y tế", "B2 - Trung cao"],
  ["administration", "/ədˌmɪn.ɪˈstreɪ.ʃən/", "Sự quản trị, ban quản lý", "Kinh doanh & Quản trị", "B2 - Trung cao"],
  ["admission", "/ədˈmɪʃ.ən/", "Sự nhận vào, vé vào cổng", "Giáo dục & Trường học", "B1 - Trung cấp"],
  ["adolescence", "/ˌæd.əˈles.əns/", "Thời thanh thiếu niên", "Tâm lý & Hành vi xã hội", "B2 - Trung cao"],
  ["adoption", "/əˈdɒp.ʃən/", "Sự thông qua, nhận nuôi", "Đời sống & Gia đình", "B1 - Trung cấp"],
  ["advancement", "/ədˈvɑːns.mənt/", "Sự tiến bộ, thăng tiến", "Kinh doanh & Quản trị", "B2 - Trung cao"],
  ["adversity", "/ədˈvɜː.sə.ti/", "Nghịch cảnh, thử thách", "Tâm lý & Hành vi xã hội", "C1 - Cao cấp"],
  ["advocate", "/ˈæd.və.kət/", "Người ủng hộ, người biện hộ", "Luật pháp & Ngoại giao", "B2 - Trung cao"],
  ["aesthetic", "/esˈθet.ɪk/", "Tính thẩm mỹ", "Nghệ thuật & Văn hóa", "B2 - Trung cao"],
  ["affection", "/əˈfek.ʃən/", "Tình cảm, sự yêu thương", "Đời sống & Gia đình", "B1 - Trung cấp"],
  ["affinity", "/əˈfɪn.ə.ti/", "Sự đồng cảm, ái lực", "Tâm lý & Hành vi xã hội", "C1 - Cao cấp"],
  ["affluence", "/ˈæf.luː.əns/", "Sự giàu có, sung túc", "Kinh tế & Tài chính", "C1 - Cao cấp"],
  ["agenda", "/əˈdʒen.də/", "Chương trình nghị sự", "Kinh doanh & Quản trị", "B1 - Trung cấp"],
  ["aggression", "/əˈɡreʃ.ən/", "Sự gây hấn, hung hăng", "Tâm lý & Hành vi xã hội", "B2 - Trung cao"],
  ["agreement", "/əˈɡriː.mənt/", "Hợp đồng, sự thỏa thuận", "Luật pháp & Ngoại giao", "A2 - Sơ cấp"],
  ["alienation", "/ˌeɪ.li.əˈneɪ.ʃən/", "Sự xa lánh, cô lập hóa", "Tâm lý & Hành vi xã hội", "C1 - Cao cấp"],
  ["alignment", "/əˈlaɪn.mənt/", "Sự liên kết, căn chỉnh", "Kinh doanh & Quản trị", "B2 - Trung cao"],
  ["allegation", "/ˌæl.əˈɡeɪ.ʃən/", "Lời cáo buộc", "Luật pháp & Ngoại giao", "C1 - Cao cấp"],
  ["alliance", "/əˈlaɪ.əns/", "Khối liên minh", "Luật pháp & Ngoại giao", "B2 - Trung cao"],
  ["allocation", "/ˌæl.əˈkeɪ.ʃən/", "Sự phân bổ nguồn lực", "Tài chính & Đầu tư", "B2 - Trung cao"],
  ["allowance", "/əˈlaʊ.əns/", "Tiền trợ cấp, định mức", "Tài chính & Đầu tư", "B1 - Trung cấp"],
  ["alteration", "/ˌɒl.təˈreɪ.ʃən/", "Sự thay đổi, biến cải", "Khoa học & Đổi mới", "B2 - Trung cao"],
  ["ambiguity", "/ˌæm.bɪˈɡjuː.ə.ti/", "Sự mơ hồ, không rõ ràng", "Triết học & Tư duy phản biện", "C1 - Cao cấp"],
  ["ambition", "/æmˈbɪʃ.ən/", "Tham vọng, hoài bão", "Giáo dục & Trường học", "B1 - Trung cấp"],
  ["amendment", "/əˈmend.mənt/", "Bản sửa đổi, bổ sung", "Luật pháp & Ngoại giao", "C1 - Cao cấp"],
  ["analogy", "/əˈnæl.ə.dʒi/", "Sự tương tự, phép loại suy", "Triết học & Tư duy phản biện", "C1 - Cao cấp"],
  ["analysis", "/əˈnæl.ə.sɪs/", "Sự phân tích", "Học thuật & Nghiên cứu", "B1 - Trung cấp"],
  ["anecdote", "/ˈæn.ɪk.dəʊt/", "Giai thoại, mẩu chuyện nhỏ", "Nghệ thuật & Văn hóa", "B2 - Trung cao"],
  ["anniversary", "/ˌæn.ɪˈvɜː.sər.i/", "Ngày kỷ niệm", "Đời sống & Gia đình", "A2 - Sơ cấp"],
  ["announcement", "/əˈnaʊns.mənt/", "Thông báo chính thức", "Truyền thông & Báo chí", "A2 - Sơ cấp"],
  ["anomaly", "/əˈnɒm.ə.li/", "Sự dị thường, bất thường", "Khoa học & Đổi mới", "C1 - Cao cấp"],
  ["anthropology", "/ˌæn.θrəˈpɒl.ə.dʒi/", "Nhân chủng học", "Học thuật & Nghiên cứu", "C1 - Cao cấp"],
  ["anticipation", "/ænˌtɪs.ɪˈpeɪ.ʃən/", "Sự kỳ vọng, trông đợi", "Tâm lý & Hành vi xã hội", "B2 - Trung cao"],
  ["anxiety", "/æŋˈzaɪ.ə.ti/", "Sự lo âu, bồn chồn", "Sức khỏe & Y tế", "B1 - Trung cấp"],
  ["apparatus", "/ˌæp.əˈreɪ.təs/", "Bộ máy, thiết bị chuyên dụng", "Khoa học & Đổi mới", "C1 - Cao cấp"],
  ["apparel", "/əˈpær.əl/", "Trang phục, may mặc", "Mua sắm & Dịch vụ", "B2 - Trung cao"],
  ["appeal", "/əˈpiːl/", "Sự kháng cáo, sức hút", "Luật pháp & Ngoại giao", "B2 - Trung cao"],
  ["appearance", "/əˈpɪə.rəns/", "Diện mạo, sự xuất hiện", "Đời sống & Gia đình", "A2 - Sơ cấp"],
  ["application", "/ˌæp.lɪˈkeɪ.ʃən/", "Ứng dụng, đơn xin việc", "Công nghệ & Kỹ thuật số", "A2 - Sơ cấp"],
  ["appointment", "/əˈpɔɪnt.mənt/", "Cuộc hẹn, sự bổ nhiệm", "Kinh doanh & Quản trị", "B1 - Trung cấp"],
  ["appreciation", "/əˌpriː.ʃiˈeɪ.ʃən/", "Sự cảm kích, tăng giá tài sản", "Tài chính & Đầu tư", "B2 - Trung cao"],
  ["apprehension", "/ˌæp.rɪˈhen.ʃən/", "Sự lo âu, e sợ", "Tâm lý & Hành vi xã hội", "C1 - Cao cấp"],
  ["approach", "/əˈprəʊtʃ/", "Cách tiếp cận, phương pháp", "Học thuật & Nghiên cứu", "B1 - Trung cấp"],
  ["appropriation", "/əˌprəʊ.priˈeɪ.ʃən/", "Sự phân bổ, chiếm đoạt", "Luật pháp & Ngoại giao", "C2 - Thành thạo"],
  ["approval", "/əˈpruː.vəl/", "Sự phê duyệt, tán thành", "Kinh doanh & Quản trị", "B1 - Trung cấp"],
  ["archetype", "/ˈɑː.kɪ.taɪp/", "Hình mẫu nguyên thủy", "Triết học & Tư duy phản biện", "C2 - Thành thạo"],
  ["architecture", "/ˈɑː.kɪ.tek.tʃər/", "Kiến trúc", "Nghệ thuật & Văn hóa", "B1 - Trung cấp"],
  ["archive", "/ˈɑː.kaɪv/", "Tài liệu lưu trữ", "Học thuật & Nghiên cứu", "B2 - Trung cao"],
  ["arithmetic", "/əˈrɪθ.mə.tɪk/", "Số học", "Giáo dục & Trường học", "B1 - Trung cấp"],
  ["arrangement", "/əˈreɪndʒ.mənt/", "Sự sắp đặt, dàn xếp", "Giao tiếp hàng ngày", "B1 - Trung cấp"],
  ["artifact", "/ˈɑː.tɪ.fækt/", "Hiện vật khảo cổ, đồ tạo tác", "Nghệ thuật & Văn hóa", "B2 - Trung cao"],
  ["articulation", "/ɑːˌtɪk.jəˈleɪ.ʃən/", "Sự phát âm rõ ràng, khớp nối", "Học thuật & Nghiên cứu", "C1 - Cao cấp"],
  ["aspiration", "/ˌæs.pɪˈreɪ.ʃən/", "Khát vọng, hoài bão lớn", "Giáo dục & Trường học", "B2 - Trung cao"],
  ["assault", "/əˈsɒlt/", "Cuộc tấn công", "Luật pháp & Ngoại giao", "B2 - Trung cao"],
  ["assembly", "/əˈsem.bli/", "Hội đồng, dây chuyền lắp ráp", "Vận tải & Hậu cần", "B2 - Trung cao"],
  ["assertion", "/əˈsɜː.ʃən/", "Sự khẳng định, quả quyết", "Triết học & Tư duy phản biện", "C1 - Cao cấp"],
  ["assessment", "/əˈses.mənt/", "Sự đánh giá", "Giáo dục & Trường học", "B1 - Trung cấp"],
  ["asset", "/ˈæs.et/", "Tài sản", "Tài chính & Đầu tư", "TOEIC 500-750"],
  ["assignment", "/əˈsaɪn.mənt/", "Nhiệm vụ, bài tập", "Giáo dục & Trường học", "A2 - Sơ cấp"],
  ["assimilation", "/əˌsɪm.ɪˈleɪ.ʃən/", "Sự đồng hóa, tiếp thu", "Tâm lý & Hành vi xã hội", "C1 - Cao cấp"],
  ["association", "/əˌsəʊ.siˈeɪ.ʃən/", "Hiệp hội, sự liên tưởng", "Kinh doanh & Quản trị", "B1 - Trung cấp"],
  ["assumption", "/əˈsʌmp.ʃən/", "Giả định", "Học thuật & Nghiên cứu", "B2 - Trung cao"],
  ["assurance", "/əˈʃɔː.rəns/", "Sự bảo đảm, cam đoan", "Kinh doanh & Quản trị", "B2 - Trung cao"],
  ["astronaut", "/ˈæs.trə.nɔːt/", "Phi hành gia", "Khoa học & Đổi mới", "B1 - Trung cấp"],
  ["astronomy", "/əˈstrɒn.ə.mi/", "Thiên văn học", "Khoa học & Đổi mới", "B2 - Trung cao"],
  ["asymmetry", "/eɪˈsɪm.ə.tri/", "Tính bất đối xứng", "Khoa học & Đổi mới", "C1 - Cao cấp"],
  ["atmosphere", "/ˈæt.məs.fɪər/", "Khí quyển, bầu không khí", "Môi trường & Sinh thái", "B1 - Trung cấp"],
  ["atrocity", "/əˈtrɒs.ə.ti/", "Hành vi tàn bạo, tội ác", "Luật pháp & Ngoại giao", "C2 - Thành thạo"],
  ["attachment", "/əˈtætʃ.mənt/", "Tệp đính kèm, sự gắn bó", "Công nghệ & Kỹ thuật số", "A2 - Sơ cấp"],
  ["attainment", "/əˈteɪn.mənt/", "Sự đạt được, thành tựu", "Giáo dục & Trường học", "C1 - Cao cấp"],
  ["attendance", "/əˈten.dəns/", "Sự tham dự, chuyên cần", "Giáo dục & Trường học", "A2 - Sơ cấp"],
  ["attitude", "/ˈæt.ɪ.tjuːd/", "Thái độ", "Tâm lý & Hành vi xã hội", "B1 - Trung cấp"],
  ["attraction", "/əˈtræk.ʃən/", "Điểm thu hút du lịch, sức hút", "Du lịch & Khách sạn", "A2 - Sơ cấp"],
  ["attribute", "/ˈæt.rɪ.bjuːt/", "Thuộc tính, đặc tính", "Học thuật & Nghiên cứu", "B2 - Trung cao"],
  ["auction", "/ˈɔːk.ʃən/", "Buổi đấu giá", "Mua sắm & Dịch vụ", "B2 - Trung cao"],
  ["audience", "/ˈɔː.di.əns/", "Khán giả", "Truyền thông & Báo chí", "A2 - Sơ cấp"],
  ["audit", "/ˈɔː.dɪt/", "Sự kiểm toán", "Tài chính & Đầu tư", "TOEIC 750+"],
  ["authenticity", "/ˌɔː.θenˈtɪs.ə.ti/", "Tính xác thực, chân thực", "Nghệ thuật & Văn hóa", "C1 - Cao cấp"],
  ["author", "/ˈɔː.θər/", "Tác giả", "Giáo dục & Trường học", "A1 - Cơ bản"],
  ["authority", "/ɔːˈθɒr.ə.ti/", "Nhà chức trách, thẩm quyền", "Luật pháp & Ngoại giao", "B1 - Trung cấp"],
  ["automation", "/ˌɔː.təˈmeɪ.ʃən/", "Sự tự động hóa", "Công nghệ & Kỹ thuật số", "B2 - Trung cao"],
  ["autonomy", "/ɔːˈtɒn.ə.mi/", "Quyền tự chủ", "Luật pháp & Ngoại giao", "C1 - Cao cấp"],
  ["availability", "/əˌveɪ.ləˈbɪl.ə.ti/", "Tính sẵn có", "Giao tiếp hàng ngày", "B1 - Trung cấp"],
  ["avenue", "/ˈæv.ə.njuː/", "Đại lộ, giải pháp", "Du lịch & Khách sạn", "A2 - Sơ cấp"],
  ["aviation", "/ˌeɪ.viˈeɪ.ʃən/", "Ngành hàng không", "Vận tải & Hậu cần", "B2 - Trung cao"],
  ["awareness", "/əˈweə.nəs/", "Nhận thức", "Tâm lý & Hành vi xã hội", "B1 - Trung cấp"],
  ["background", "/ˈbæk.ɡraʊnd/", "Bối cảnh, nền tảng học vấn", "Nhân sự & Tuyển dụng", "A2 - Sơ cấp"],
  ["backup", "/ˈbæk.ʌp/", "Bản sao lưu dự phòng", "Công nghệ & Kỹ thuật số", "B1 - Trung cấp"],
  ["balance", "/ˈbæl.əns/", "Sự cân bằng, số dư tài khoản", "Tài chính & Đầu tư", "A2 - Sơ cấp"],
  ["barrier", "/ˈbær.i.ər/", "Rào cản", "Kinh tế & Tài chính", "B1 - Trung cấp"],
  ["baseline", "/ˈbeɪs.laɪn/", "Mức chuẩn cơ sở", "Khoa học & Đổi mới", "B2 - Trung cao"],
  ["behavior", "/bɪˈheɪ.vjər/", "Hành vi", "Tâm lý & Hành vi xã hội", "A2 - Sơ cấp"],
  ["benchmark", "/ˈbentʃ.mɑːk/", "Tiêu chuẩn đánh giá", "Kinh doanh & Quản trị", "B2 - Trung cao"],
  ["beneficiary", "/ˌben.ɪˈfɪʃ.ər.i/", "Người thụ hưởng", "Luật pháp & Ngoại giao", "C1 - Cao cấp"],
  ["biodiversity", "/ˌbaɪ.əʊ.daɪˈvɜː.sə.ti/", "Đa dạng sinh học", "Môi trường & Sinh thái", "B2 - Trung cao"],
  ["biography", "/baɪˈɒɡ.rə.fi/", "Tiểu sử", "Nghệ thuật & Văn hóa", "B1 - Trung cấp"],
  ["biotechnology", "/ˌbaɪ.əʊ.tekˈnɒl.ə.dʒi/", "Công nghệ sinh học", "Khoa học & Đổi mới", "C1 - Cao cấp"],
  ["blockade", "/blɒkˈeɪd/", "Sự phong tỏa", "Luật pháp & Ngoại giao", "C1 - Cao cấp"],
  ["blueprint", "/ˈbluː.prɪnt/", "Bản thiết kế chi tiết", "Công nghệ & Kỹ thuật số", "B2 - Trung cao"],
  ["bottleneck", "/ˈbɒt.əl.nek/", "Điểm nghẽn cổ chai", "Kinh doanh & Quản trị", "B2 - Trung cao"],
  ["boundary", "/ˈbaʊn.dər.i/", "Ranh giới, biên giới", "Môi trường & Sinh thái", "B1 - Trung cấp"],
  ["breakthrough", "/ˈbreɪk.θruː/", "Bước đột phá", "Khoa học & Đổi mới", "B2 - Trung cao"],
  ["broadband", "/ˈbrɔːd.bænd/", "Băng thông rộng", "Công nghệ & Kỹ thuật số", "B1 - Trung cấp"],
  ["broadcast", "/ˈbrɔːd.kɑːst/", "Chương trình phát sóng", "Truyền thông & Báo chí", "B1 - Trung cấp"],
  ["brokerage", "/ˈbrəʊ.kər.ɪdʒ/", "Dịch vụ môi giới", "Tài chính & Đầu tư", "TOEIC 750+"],
  ["budget", "/ˈbʌdʒ.ɪt/", "Ngân sách", "Tài chính & Đầu tư", "A2 - Sơ cấp"],
  ["buffer", "/ˈbʌf.ər/", "Bộ đệm, vùng đệm", "Công nghệ & Kỹ thuật số", "B2 - Trung cao"],
  ["bureaucracy", "/bjʊəˈrɒk.rə.si/", "Bộ máy quan liêu", "Kinh doanh & Quản trị", "C1 - Cao cấp"],
  ["byproduct", "/ˈbaɪˌprɒd.ʌkt/", "Sản phẩm phụ", "Môi trường & Sinh thái", "B2 - Trung cao"],
  ["calibration", "/ˌkæl.ɪˈbreɪ.ʃən/", "Sự hiệu chuẩn", "Khoa học & Đổi mới", "C1 - Cao cấp"],
  ["campaign", "/kæmˈpeɪn/", "Chiến dịch", "Kinh doanh & Quản trị", "B1 - Trung cấp"],
  ["candidate", "/ˈkæn.dɪ.dət/", "Ứng viên", "Nhân sự & Tuyển dụng", "A2 - Sơ cấp"],
  ["capacity", "/kəˈpæs.ə.ti/", "Sức chứa, công suất", "Kinh tế & Tài chính", "B1 - Trung cấp"],
  ["capitalism", "/ˈkæp.ɪ.təl.ɪ.zəm/", "Chủ nghĩa tư bản", "Kinh tế & Tài chính", "B2 - Trung cao"],
  ["carbon", "/ˈkɑː.bən/", "Nguyên tố cacbon", "Môi trường & Sinh thái", "A2 - Sơ cấp"],
  ["cargo", "/ˈkɑː.ɡəʊ/", "Hàng hóa vận chuyển", "Vận tải & Hậu cần", "TOEIC 500-750"],
  ["catalyst", "/ˈkæt.əl.ɪst/", "Chất xúc tác", "Khoa học & Đổi mới", "C1 - Cao cấp"],
  ["catastrophe", "/kəˈtæs.trə.fi/", "Thảm họa lớn", "Môi trường & Sinh thái", "C1 - Cao cấp"],
  ["category", "/ˈkæt.ə.ɡri/", "Danh mục, thể loại", "Giao tiếp hàng ngày", "A2 - Sơ cấp"],
  ["caution", "/ˈkɔː.ʃən/", "Sự cẩn trọng", "Giao tiếp hàng ngày", "B1 - Trung cấp"],
  ["census", "/ˈsen.səs/", "Cuộc điều tra dân số", "Học thuật & Nghiên cứu", "C1 - Cao cấp"],
  ["certainty", "/ˈsɜː.tən.ti/", "Sự chắc chắn", "Triết học & Tư duy phản biện", "B2 - Trung cao"],
  ["certificate", "/səˈtɪf.ɪ.kət/", "Chứng chỉ, văn bằng", "Giáo dục & Trường học", "A2 - Sơ cấp"],
  ["champion", "/ˈtʃæm.pi.ən/", "Nhà vô địch, người tiên phong", "Đời sống & Gia đình", "A2 - Sơ cấp"],
  ["championship", "/ˈtʃæm.pi.ən.ʃɪp/", "Giải vô địch", "Đời sống & Gia đình", "A2 - Sơ cấp"],
  ["chancellor", "/ˈtʃɑːn.səl.ər/", "Hiệu trưởng đại học, thủ tướng", "Giáo dục & Trường học", "C1 - Cao cấp"],
  ["channel", "/ˈtʃæn.əl/", "Kênh truyền thông, luồng", "Truyền thông & Báo chí", "A2 - Sơ cấp"],
  ["chaos", "/ˈkeɪ.ɒs/", "Sự hỗn loạn", "Tâm lý & Hành vi xã hội", "B2 - Trung cao"],
  ["characteristic", "/ˌkær.ək.təˈrɪs.tɪk/", "Đặc tính, nét đặc trưng", "Học thuật & Nghiên cứu", "B1 - Trung cấp"],
  ["charity", "/ˈtʃær.ə.ti/", "Hội từ thiện", "Tâm lý & Hành vi xã hội", "A2 - Sơ cấp"],
  ["charter", "/ˈtʃɑː.tər/", "Hiến chương, điều lệ", "Luật pháp & Ngoại giao", "C1 - Cao cấp"],
  ["checklist", "/ˈtʃek.lɪst/", "Danh sách kiểm tra", "Kinh doanh & Quản trị", "A2 - Sơ cấp"],
  ["checkpoint", "/ˈtʃek.pɔɪnt/", "Trạm kiểm soát", "Vận tải & Hậu cần", "B1 - Trung cấp"],
  ["chronicle", "/ˈkrɒn.ɪ.kəl/", "Biên niên sử", "Nghệ thuật & Văn hóa", "C1 - Cao cấp"],
  ["chronology", "/krəˈnɒl.ə.dʒi/", "Trình tự thời gian", "Học thuật & Nghiên cứu", "C1 - Cao cấp"],
  ["circuit", "/ˈsɜː.kɪt/", "Mạch điện, vòng quanh", "Công nghệ & Kỹ thuật số", "B1 - Trung cấp"],
  ["circulation", "/ˌsɜː.kjəˈleɪ.ʃən/", "Sự lưu thông, số lượng phát hành", "Kinh tế & Tài chính", "B2 - Trung cao"],
  ["circumstance", "/ˈsɜː.kəm.stɑːns/", "Hoàn cảnh, tình huống", "Đời sống & Gia đình", "B1 - Trung cấp"],
  ["citation", "/saɪˈteɪ.ʃən/", "Trích dẫn khoa học", "Học thuật & Nghiên cứu", "B2 - Trung cao"],
  ["citizen", "/ˈsɪt.ɪ.zən/", "Công dân", "Luật pháp & Ngoại giao", "A2 - Sơ cấp"],
  ["citizenship", "/ˈsɪt.ɪ.zən.ʃɪp/", "Quyền công dân, quốc tịch", "Luật pháp & Ngoại giao", "B1 - Trung cấp"],
  ["civilization", "/ˌsɪv.əl.aɪˈzeɪ.ʃən/", "Nền văn minh", "Nghệ thuật & Văn hóa", "B2 - Trung cao"],
  ["clarification", "/ˌklær.ɪ.fɪˈkeɪ.ʃən/", "Sự làm rõ, giải thích", "Giao tiếp hàng ngày", "B2 - Trung cao"],
  ["clarity", "/ˈklær.ə.ti/", "Sự rõ ràng, sáng sủa", "Triết học & Tư duy phản biện", "B2 - Trung cao"],
  ["classification", "/ˌklæs.ɪ.fɪˈkeɪ.ʃən/", "Sự phân loại", "Khoa học & Đổi mới", "B2 - Trung cao"],
  ["client", "/ˈklaɪ.ənt/", "Khách hàng doanh nghiệp", "Kinh doanh & Quản trị", "A2 - Sơ cấp"],
  ["climate", "/ˈklaɪ.mət/", "Khí hậu", "Môi trường & Sinh thái", "A1 - Cơ bản"],
  ["clinic", "/ˈklɪn.ɪk/", "Phòng khám", "Sức khỏe & Y tế", "A2 - Sơ cấp"],
  ["cluster", "/ˈklʌs.tər/", "Cụm, chùm liên kết", "Công nghệ & Kỹ thuật số", "B2 - Trung cao"],
  ["coalition", "/ˌkəʊ.əˈlɪʃ.ən/", "Khối liên minh chính trị", "Luật pháp & Ngoại giao", "C1 - Cao cấp"],
  ["code", "/kəʊd/", "Mã nguồn, bộ luật", "Công nghệ & Kỹ thuật số", "A1 - Cơ bản"],
  ["cognition", "/kɒɡˈnɪʃ.ən/", "Nhận thức", "Tâm lý & Hành vi xã hội", "C1 - Cao cấp"],
  ["coherence", "/kəʊˈhɪə.rəns/", "Tính mạch lạc, gắn kết", "Triết học & Tư duy phản biện", "C1 - Cao cấp"],
  ["cohesion", "/kəʊˈhiː.ʒən/", "Sự liên kết chặt chẽ", "Tâm lý & Hành vi xã hội", "B2 - Trung cao"],
  ["collaboration", "/kəˌlæb.əˈreɪ.ʃən/", "Sự hợp tác", "Kinh doanh & Quản trị", "B1 - Trung cấp"],
  ["collapse", "/kəˈlæps/", "Sự sụp đổ", "Kinh tế & Tài chính", "B2 - Trung cao"],
  ["colleague", "/ˈkɒl.iːɡ/", "Đồng nghiệp", "Nhân sự & Tuyển dụng", "A2 - Sơ cấp"],
  ["collection", "/kəˈlek.ʃən/", "Bộ sưu tập, sự thu gom", "Nghệ thuật & Văn hóa", "A2 - Sơ cấp"],
  ["colloquium", "/kəˈləʊ.kwi.əm/", "Hội thảo chuyên đề", "Học thuật & Nghiên cứu", "C2 - Thành thạo"],
  ["colonization", "/ˌkɒl.ə.naɪˈzeɪ.ʃən/", "Sự thuộc địa hóa", "Học thuật & Nghiên cứu", "C1 - Cao cấp"],
  ["columnist", "/ˈkɒl.əm.nɪst/", "Nhà bình luận báo chí", "Truyền thông & Báo chí", "B2 - Trung cao"],
  ["combat", "/ˈkɒm.bæt/", "Trận chiến đấu", "Luật pháp & Ngoại giao", "B2 - Trung cao"],
  ["combination", "/ˌkɒm.bɪˈneɪ.ʃən/", "Sự phối hợp, kết hợp", "Giao tiếp hàng ngày", "A2 - Sơ cấp"],
  ["comfort", "/ˈkʌm.fət/", "Sự thoải mái, an ủi", "Đời sống & Gia đình", "A2 - Sơ cấp"],
  ["commander", "/kəˈmɑːn.dər/", "Chỉ huy trưởng", "Luật pháp & Ngoại giao", "B2 - Trung cao"],
  ["commemoration", "/kəˌmem.əˈreɪ.ʃən/", "Lễ tưởng niệm", "Nghệ thuật & Văn hóa", "C1 - Cao cấp"],
  ["commencement", "/kəˈmens.mənt/", "Lễ tốt nghiệp, sự khởi đầu", "Giáo dục & Trường học", "C1 - Cao cấp"],
  ["commentary", "/ˈkɒm.ən.tər.i/", "Bài bình luận", "Truyền thông & Báo chí", "B2 - Trung cao"],
  ["commerce", "/ˈkɒm.ɜːs/", "Thương mại", "Kinh tế & Tài chính", "B1 - Trung cấp"],
  ["commission", "/kəˈmɪʃ.ən/", "Ủy ban, tiền hoa hồng", "Kinh doanh & Quản trị", "B1 - Trung cấp"],
  ["commitment", "/kəˈmɪt.mənt/", "Sự cam kết tận tâm", "Kinh doanh & Quản trị", "B1 - Trung cấp"],
  ["commodity", "/kəˈmɒd.ə.ti/", "Hàng hóa thương phẩm", "Kinh tế & Tài chính", "B2 - Trung cao"],
  ["communication", "/kəˌmjuː.nɪˈkeɪ.ʃən/", "Sự giao tiếp, liên lạc", "Giao tiếp hàng ngày", "A2 - Sơ cấp"],
  ["community", "/kəˈmjuː.nə.ti/", "Cộng đồng", "Tâm lý & Hành vi xã hội", "A2 - Sơ cấp"],
  ["companion", "/kəmˈpæn.jən/", "Người bạn đồng hành", "Đời sống & Gia đình", "B1 - Trung cấp"],
  ["company", "/ˈkʌm.pə.ni/", "Công ty, bạn bè cùng đi", "Kinh doanh & Quản trị", "A1 - Cơ bản"],
  ["comparison", "/kəmˈpær.ɪ.sən/", "Sự so sánh", "Học thuật & Nghiên cứu", "B1 - Trung cấp"],
  ["compassion", "/kəmˈpæʃ.ən/", "Lòng trắc ẩn", "Tâm lý & Hành vi xã hội", "B2 - Trung cao"],
  ["compatibility", "/kəmˌpæt.əˈbɪl.ə.ti/", "Tính tương thích", "Công nghệ & Kỹ thuật số", "B2 - Trung cao"],
  ["compensation", "/ˌkɒm.penˈseɪ.ʃən/", "Sự bồi thường, thù lao", "Nhân sự & Tuyển dụng", "B2 - Trung cao"],
  ["competence", "/ˈkɒm.pɪ.təns/", "Năng lực, thẩm quyền", "Nhân sự & Tuyển dụng", "B2 - Trung cao"],
  ["competition", "/ˌkɒm.pəˈtɪʃ.ən/", "Cuộc thi, sự cạnh tranh", "Kinh doanh & Quản trị", "A2 - Sơ cấp"],
  ["competitor", "/kəmˈpet.ɪ.tər/", "Đối thủ cạnh tranh", "Kinh doanh & Quản trị", "B1 - Trung cấp"],
  ["compilation", "/ˌkɒm.pɪˈleɪ.ʃən/", "Sự biên tập, tổng hợp", "Học thuật & Nghiên cứu", "B2 - Trung cao"],
  ["complaint", "/kəmˈpleɪnt/", "Lời phàn nàn, khiếu nại", "Mua sắm & Dịch vụ", "A2 - Sơ cấp"],
  ["complement", "/ˈkɒm.plɪ.mənt/", "Phần bổ sung, bổ ngữ", "Học thuật & Nghiên cứu", "B2 - Trung cao"],
  ["completion", "/kəmˈpliː.ʃən/", "Sự hoàn tất", "Kinh doanh & Quản trị", "B1 - Trung cấp"],
  ["complexity", "/kəmˈplek.sə.ti/", "Sự phức tạp", "Khoa học & Đổi mới", "B2 - Trung cao"],
  ["compliance", "/kəmˈplaɪ.əns/", "Sự tuân thủ pháp lý", "Luật pháp & Ngoại giao", "TOEIC 750+"],
  ["component", "/kəmˈpəʊ.nənt/", "Thành phần linh kiện", "Công nghệ & Kỹ thuật số", "B2 - Trung cao"],
  ["composer", "/kəmˈpəʊ.zər/", "Nhà soạn nhạc", "Nghệ thuật & Văn hóa", "A2 - Sơ cấp"],
  ["composition", "/ˌkɒm.pəˈzɪʃ.ən/", "Cấu trúc, bài văn", "Nghệ thuật & Văn hóa", "B1 - Trung cấp"],
  ["compound", "/ˈkɒm.paʊnd/", "Hợp chất, khuôn viên", "Khoa học & Đổi mới", "B1 - Trung cấp"],
  ["comprehension", "/ˌkɒm.prɪˈhen.ʃən/", "Khả năng đọc hiểu", "Giáo dục & Trường học", "B1 - Trung cấp"],
  ["compromise", "/ˈkɒm.prə.maɪz/", "Sự thỏa hiệp", "Kinh doanh & Quản trị", "B2 - Trung cao"],
  ["computation", "/ˌkɒm.pjuːˈteɪ.ʃən/", "Sự tính toán điện toán", "Công nghệ & Kỹ thuật số", "B2 - Trung cao"],
  ["computer", "/kəmˈpjuː.tər/", "Máy vi tính", "Công nghệ & Kỹ thuật số", "A1 - Cơ bản"],
  ["concentration", "/ˌkɒn.sənˈtreɪ.ʃən/", "Sự tập trung, nồng độ", "Khoa học & Đổi mới", "B1 - Trung cấp"],
  ["concept", "/ˈkɒn.sept/", "Khái niệm", "Học thuật & Nghiên cứu", "B1 - Trung cấp"],
  ["conception", "/kənˈsep.ʃən/", "Sự thụ thai, quan niệm", "Triết học & Tư duy phản biện", "C1 - Cao cấp"],
  ["concern", "/kənˈsɜːn/", "Mối bận tâm, lo ngại", "Giao tiếp hàng ngày", "B1 - Trung cấp"],
  ["concert", "/ˈkɒn.sət/", "Buổi hòa nhạc", "Nghệ thuật & Văn hóa", "A1 - Cơ bản"],
  ["concession", "/kənˈseʃ.ən/", "Sự nhượng bộ, quầy dịch vụ", "Luật pháp & Ngoại giao", "C1 - Cao cấp"],
  ["conclusion", "/kənˈkluː.ʒən/", "Kết luận", "Học thuật & Nghiên cứu", "A2 - Sơ cấp"],
  ["concordance", "/kənˈkɔː.dəns/", "Sự tương thích, bảng đối chiếu", "Học thuật & Nghiên cứu", "C2 - Thành thạo"],
  ["condition", "/kənˈdɪʃ.ən/", "Điều kiện, tình trạng", "Giao tiếp hàng ngày", "A2 - Sơ cấp"],
  ["conduct", "/ˈkɒn.dʌkt/", "Hành vi, tư cách", "Kinh doanh & Quản trị", "B2 - Trung cao"],
  ["conductor", "/kənˈdʌk.tər/", "Nhạc trưởng, chất dẫn điện", "Khoa học & Đổi mới", "B1 - Trung cấp"],
  ["conference", "/ˈkɒn.fər.əns/", "Hội nghị", "Kinh doanh & Quản trị", "A2 - Sơ cấp"],
  ["confidence", "/ˈkɒn.fɪ.dəns/", "Sự tự tin, lòng tin", "Tâm lý & Hành vi xã hội", "A2 - Sơ cấp"],
  ["configuration", "/kənˌfɪɡ.jəˈreɪ.ʃən/", "Cấu hình hệ thống", "Công nghệ & Kỹ thuật số", "B2 - Trung cao"],
  ["confirmation", "/ˌkɒn.fəˈmeɪ.ʃən/", "Sự xác nhận", "Giao tiếp hàng ngày", "B1 - Trung cấp"],
  ["conflict", "/ˈkɒn.flɪkt/", "Xung đột, mâu thuẫn", "Luật pháp & Ngoại giao", "B1 - Trung cấp"],
  ["conformity", "/kənˈfɔː.mə.ti/", "Sự tuân theo lề thói", "Tâm lý & Hành vi xã hội", "C1 - Cao cấp"],
  ["confrontation", "/ˌkɒn.frʌnˈteɪ.ʃən/", "Sự đối đầu", "Luật pháp & Ngoại giao", "B2 - Trung cao"],
  ["confusion", "/kənˈfjuː.ʒən/", "Sự bối rối, nhầm lẫn", "Giao tiếp hàng ngày", "B1 - Trung cấp"],
  ["congestion", "/kənˈdʒes.tʃən/", "Sự tắc nghẽn giao thông", "Vận tải & Hậu cần", "B1 - Trung cấp"],
  ["congratulation", "/kənˌɡrætʃ.əˈleɪ.ʃən/", "Lời chúc mừng", "Giao tiếp hàng ngày", "A2 - Sơ cấp"],
  ["congress", "/ˈkɒŋ.ɡres/", "Quốc hội, đại hội", "Luật pháp & Ngoại giao", "B2 - Trung cao"],
  ["conjunction", "/kənˈdʒʌŋk.ʃən/", "Liên từ, sự kết hợp", "Giáo dục & Trường học", "B1 - Trung cấp"],
  ["connection", "/kəˈnek.ʃən/", "Sự kết nối, mối quan hệ", "Công nghệ & Kỹ thuật số", "A2 - Sơ cấp"],
  ["connotation", "/ˌkɒn.əˈteɪ.ʃən/", "Ý nghĩa hàm ẩn", "Học thuật & Nghiên cứu", "C1 - Cao cấp"],
  ["conscience", "/ˈkɒn.ʃəns/", "Lương tâm", "Triết học & Tư duy phản biện", "B2 - Trung cao"],
  ["consciousness", "/ˈkɒn.ʃəs.nəs/", "Ý thức, nhận thức", "Tâm lý & Hành vi xã hội", "B2 - Trung cao"],
  ["consensus", "/kənˈsen.səs/", "Sự đồng thuận chung", "Kinh doanh & Quản trị", "C1 - Cao cấp"],
  ["consent", "/kənˈsent/", "Sự ưng thuận, chấp thuận", "Luật pháp & Ngoại giao", "B2 - Trung cao"],
  ["consequence", "/ˈkɒn.sɪ.kwəns/", "Hậu quả, kết quả", "Môi trường & Sinh thái", "B1 - Trung cấp"],
  ["conservation", "/ˌkɒn.səˈveɪ.ʃən/", "Sự bảo tồn", "Môi trường & Sinh thái", "B2 - Trung cao"],
  ["consistency", "/kənˈsɪs.tən.si/", "Tính nhất quán, kiên định", "Kinh doanh & Quản trị", "B2 - Trung cao"],
  ["consolidation", "/kənˌsɒl.ɪˈdeɪ.ʃən/", "Sự củng cố, hợp nhất", "Tài chính & Đầu tư", "C1 - Cao cấp"],
  ["conspiracy", "/kənˈspɪr.ə.si/", "Âm mưu", "Luật pháp & Ngoại giao", "B2 - Trung cao"],
  ["constitution", "/ˌkɒn.stɪˈtjuː.ʃən/", "Hiến pháp", "Luật pháp & Ngoại giao", "B2 - Trung cao"],
  ["constraint", "/kənˈstreɪnt/", "Sự ràng buộc, hạn chế", "Kinh doanh & Quản trị", "B2 - Trung cao"],
  ["construction", "/kənˈstrʌk.ʃən/", "Công trình xây dựng", "Kinh tế & Tài chính", "A2 - Sơ cấp"],
  ["consultant", "/kənˈsʌl.tənt/", "Chuyên viên tư vấn", "Kinh doanh & Quản trị", "B1 - Trung cấp"],
  ["consultation", "/ˌkɒn.sʌlˈteɪ.ʃən/", "Cuộc hội đàm, tư vấn", "Sức khỏe & Y tế", "B2 - Trung cao"],
  ["consumer", "/kənˈsjuː.mər/", "Người tiêu dùng", "Kinh tế & Tài chính", "A2 - Sơ cấp"],
  ["consumption", "/kənˈsʌmp.ʃən/", "Sự tiêu thụ", "Kinh tế & Tài chính", "B2 - Trung cao"],
  ["contagion", "/kənˈteɪ.dʒən/", "Sự lây nhiễm dịch bệnh", "Sức khỏe & Y tế", "C1 - Cao cấp"],
  ["container", "/kənˈteɪ.nər/", "Thùng chứa, công-ten-nơ", "Vận tải & Hậu cần", "A2 - Sơ cấp"],
  ["contamination", "/kənˌtæm.ɪˈneɪ.ʃən/", "Sự ô nhiễm độc hại", "Môi trường & Sinh thái", "B2 - Trung cao"],
  ["contemplation", "/ˌkɒn.təmˈpleɪ.ʃən/", "Sự trầm tư, chiêm nghiệm", "Triết học & Tư duy phản biện", "C1 - Cao cấp"],
  ["contemporary", "/kənˈtem.pər.ər.i/", "Người cùng thời, đương đại", "Nghệ thuật & Văn hóa", "B2 - Trung cao"],
  ["contempt", "/kənˈtempt/", "Sự khinh miệt", "Tâm lý & Hành vi xã hội", "C1 - Cao cấp"],
  ["contender", "/kənˈten.dər/", "Ứng cử viên đối thủ", "Đời sống & Gia đình", "B2 - Trung cao"],
  ["contentment", "/kənˈtent.mənt/", "Sự mãn nguyện, hài lòng", "Tâm lý & Hành vi xã hội", "B2 - Trung cao"],
  ["context", "/ˈkɒn.tekst/", "Bối cảnh, ngữ cảnh", "Học thuật & Nghiên cứu", "B1 - Trung cấp"],
  ["continent", "/ˈkɒn.tɪ.nənt/", "Châu lục", "Môi trường & Sinh thái", "A2 - Sơ cấp"],
  ["contingency", "/kənˈtɪn.dʒən.si/", "Kế hoạch dự phòng", "Kinh doanh & Quản trị", "C1 - Cao cấp"],
  ["continuity", "/ˌkɒn.tɪˈnjuː.ə.ti/", "Tính liên tục", "Kinh doanh & Quản trị", "B2 - Trung cao"],
  ["contract", "/ˈkɒn.trækt/", "Hợp đồng kinh tế", "Luật pháp & Ngoại giao", "A2 - Sơ cấp"],
  ["contradiction", "/ˌkɒn.trəˈdɪk.ʃən/", "Sự mâu thuẫn", "Triết học & Tư duy phản biện", "B2 - Trung cao"],
  ["contribution", "/ˌkɒn.trɪˈbjuː.ʃən/", "Sự đóng góp, cống hiến", "Tâm lý & Hành vi xã hội", "B1 - Trung cấp"],
  ["controversy", "/ˈkɒn.trə.vɜː.si/", "Cuộc tranh cãi nảy lửa", "Truyền thông & Báo chí", "B2 - Trung cao"],
  ["convenience", "/kənˈviː.ni.əns/", "Sự tiện lợi", "Mua sắm & Dịch vụ", "B1 - Trung cấp"],
  ["convention", "/kənˈven.ʃən/", "Quy ước, hội nghị thường niên", "Nghệ thuật & Văn hóa", "B2 - Trung cao"],
  ["convergence", "/kənˈvɜː.dʒəns/", "Sự hội tụ", "Khoa học & Đổi mới", "C1 - Cao cấp"],
  ["conversation", "/ˌkɒn.vəˈseɪ.ʃən/", "Cuộc trò chuyện", "Giao tiếp hàng ngày", "A1 - Cơ bản"],
  ["conversion", "/kənˈvɜː.ʃən/", "Sự chuyển đổi", "Kinh doanh & Quản trị", "B2 - Trung cao"],
  ["conviction", "/kənˈvɪk.ʃən/", "Sức thuyết phục, niềm tin vững chắc", "Tâm lý & Hành vi xã hội", "B2 - Trung cao"],
  ["cooperation", "/kəʊˌɒp.ərˈeɪ.ʃən/", "Sự hợp tác", "Kinh doanh & Quản trị", "B1 - Trung cấp"],
  ["coordination", "/kəʊˌɔː.dɪˈneɪ.ʃən/", "Sự phối hợp, điều phối", "Kinh doanh & Quản trị", "B2 - Trung cao"],
  ["copyright", "/ˈkɒp.i.raɪt/", "Bản quyền tác giả", "Luật pháp & Ngoại giao", "B1 - Trung cấp"],
  ["corporation", "/ˌkɔː.pərˈeɪ.ʃən/", "Tập đoàn kinh tế", "Kinh doanh & Quản trị", "B1 - Trung cấp"],
  ["correlation", "/ˌkɒr.əˈleɪ.ʃən/", "Mối tương quan", "Học thuật & Nghiên cứu", "C1 - Cao cấp"],
  ["correspondence", "/ˌkɒr.ɪˈspɒn.dəns/", "Thư tín thương mại, sự tương ứng", "Kinh doanh & Quản trị", "B2 - Trung cao"],
  ["corridor", "/ˈkɒr.ɪ.dɔːr/", "Hành lang", "Du lịch & Khách sạn", "A2 - Sơ cấp"],
  ["corruption", "/kəˈrʌp.ʃən/", "Sự tham nhũng", "Luật pháp & Ngoại giao", "B2 - Trung cao"],
  ["cosmetics", "/kɒzˈmet.ɪks/", "Mỹ phẩm", "Mua sắm & Dịch vụ", "A2 - Sơ cấp"],
  ["costume", "/ˈkɒs.tjuːm/", "Trang phục biểu diễn", "Nghệ thuật & Văn hóa", "A2 - Sơ cấp"],
  ["counselor", "/ˈkaʊn.səl.ər/", "Chuyên viên tư vấn tâm lý", "Sức khỏe & Y tế", "B1 - Trung cấp"],
  ["counterpart", "/ˈkaʊn.tə.pɑːt/", "Đối tác tương đương", "Luật pháp & Ngoại giao", "C1 - Cao cấp"],
  ["courage", "/ˈkʌr.ɪdʒ/", "Lòng can đảm", "Tâm lý & Hành vi xã hội", "A2 - Sơ cấp"],
  ["courtesy", "/ˈkɜː.tə.si/", "Sự lịch thiệp, nhã nhặn", "Giao tiếp hàng ngày", "B2 - Trung cao"],
  ["coverage", "/ˈkʌv.ər.ɪdʒ/", "Phạm vi đưa tin, độ bao phủ bảo hiểm", "Truyền thông & Báo chí", "B2 - Trung cao"],
  ["creativity", "/ˌkriː.eɪˈtɪv.ə.ti/", "Sự sáng tạo", "Nghệ thuật & Văn hóa", "A2 - Sơ cấp"],
  ["credentials", "/krɪˈden.ʃəlz/", "Văn bằng chứng chỉ, uy tín", "Nhân sự & Tuyển dụng", "B2 - Trung cao"],
  ["credibility", "/ˌkred.əˈbɪl.ə.ti/", "Độ tin cậy", "Truyền thông & Báo chí", "B2 - Trung cao"],
  ["criterion", "/kraɪˈtɪə.ri.ən/", "Tiêu chí đánh giá", "Học thuật & Nghiên cứu", "B2 - Trung cao"],
  ["criticism", "/ˈkrɪt.ɪ.sɪ.zəm/", "Sự phê bình, chỉ trích", "Truyền thông & Báo chí", "B1 - Trung cấp"],
  ["cryptocurrency", "/ˈkrɪp.təʊˌkʌr.ən.si/", "Tiền mã hóa kỹ thuật số", "Tài chính & Đầu tư", "B2 - Trung cao"],
  ["cultivation", "/ˌkʌl.tɪˈveɪ.ʃən/", "Sự canh tác, trau dồi", "Môi trường & Sinh thái", "B2 - Trung cao"],
  ["culture", "/ˈkʌl.tʃər/", "Văn hóa", "Nghệ thuật & Văn hóa", "A1 - Cơ bản"],
  ["curiosity", "/ˌkjʊə.riˈɒs.ə.ti/", "Sự tò mò, hiếu kỳ", "Tâm lý & Hành vi xã hội", "B1 - Trung cấp"],
  ["currency", "/ˈkʌr.ən.si/", "Tiền tệ", "Tài chính & Đầu tư", "A2 - Sơ cấp"],
  ["curriculum", "/kəˈrɪk.jə.ləm/", "Chương trình giảng dạy", "Giáo dục & Trường học", "B2 - Trung cao"],
  ["custody", "/ˈkʌs.tə.di/", "Quyền nuôi con, tạm giam", "Luật pháp & Ngoại giao", "C1 - Cao cấp"],
  ["customer", "/ˈkʌs.tə.mər/", "Khách hàng", "Kinh doanh & Quản trị", "A1 - Cơ bản"],
  ["customization", "/ˌkʌs.tə.maɪˈzeɪ.ʃən/", "Sự tùy biến theo yêu cầu", "Công nghệ & Kỹ thuật số", "B2 - Trung cao"],
  ["cybersecurity", "/ˌsaɪ.bə.sɪˈkjʊə.rə.ti/", "An ninh mạng", "Công nghệ & Kỹ thuật số", "B2 - Trung cao"],
  ["cylinder", "/ˈsɪl.ɪn.dər/", "Hình trụ, xi lanh", "Khoa học & Đổi mới", "B2 - Trung cao"]
];

console.log(`Building seed lexicon with programmatic expansion to 10,000 distinct items...`);
